color_detector_node:
  ros__parameters:
    use_sim_time: true
    rgb_topic: '/depth_camera/image_raw'
    depth_topic: '/depth_camera/depth/image_raw'
    camera_info_topic: '/depth_camera/camera_info'
    base_frame: 'panda_link0'
    camera_frame: 'camera_color_optical_frame'
    pixel_threshold: 1500
    dedup_threshold: 0.05
    min_confidence: 0.5
    depth_scale: 1.0